skills_database = [
    "python",
    "sql",
    "machine learning",
    "power bi",
    "excel",
    "html",
    "css",
    "javascript",
    "java",
    "c++",
    "data analysis",
    "communication",
    "teamwork",
    "leadership",
    "problem solving",
    "deep learning",
    "artificial intelligence",
    "pandas",
    "numpy",
    "react",
    "flask",
    "django"
]